import 'package:get/get.dart';

class MyLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "ar": {
          "1": "تطبيق شوكولا",
          "2": "متابعة",
          "3": " تسوق من",
          "4": "الصفحة الرئيسية",
          "5": "الاعدادات",
          "6": "تسجيل خروج",
          "7": "حول",
          "8": "الوضع المظلم",
          "9": "اللغة",
          "10" : "تأكيد تسجيل الخروج",
          "11" : "هل متاكد من تسجبل الخروج؟",
          "12" : "نعم",
          "13" : "الغاء",
          "14" : "اختار منتج",
          "15" : "دفع سهل وآمن",
          "16" : "توصيل سريع",
          "17" : "المنتج الخاص بك من لدينا \n متجر الشوكولا لدينا منتج 100 ألف، اختر \n ",
          "18" : "منتج",
          "19" : "تسجيل دخول",
          "20" : "الايميل",
          "21" : "من فضلك ادخل الايميل",
          "22" : "كلمة المرور",
          "23" : "من فضلك ادخل كلمة المرور",
          "24" : "هل نسيت كلمة المرور؟",
          "25" : "هل ليس لديك حساب؟",
          "26" : "انشاء حساب",
          "27" : "نسيت كلمة المرور",
          "28" : "أدخل بريدك الإلكتروني لعملية التحقق، وسنرسل رمزًا مكونًا من 4 أرقام إلى بريدك الإلكتروني.",
          "29" : "أدخل الرمز المكون من 4 أرقام",
          "30" : "أدخل الرمز المكون من 4 أرقام \n الذي تلقيته على بريدك الإلكتروني.",
          "31" : "الكود",
          "32" : "من فضلك الكود غير صحيح.",
          "33" : " إنشاء حساب جديد",
          "34" : "يرجى ملء حقل الإدخال هنا",
          "35" : "الاسم الأول",
          "36" : "من فضلك ادخل الاسم الأول",
          "37" : "من فضلك ادخل الاسم الأخير",
          "38" : "الاسم الأخير",
          "39" : "انشاء حساب",
          "40" : "رقم الهاتف",
          "41" : "من فضلك ادخل رقم الهاتف",
          "42" : "اعادة تعيين كلمة المرور",
          "43" : "اعادة تعيين كلمة المرور",
          "44" : "تأكيد كلمة المرور",

        },

        "en": {
          "1": "Chocolate App",
          "2": "Continue",
          "3": "Shopping From",
          "4": "Home Page",
          "5": "Settings",
          "6": "Log Out",
          "7": "About",
          "8": "Dark Mode",
          "9": "Language",
          "10": "Confirm logout",
          "11": "Are you sure to logout ?",
          "12": "Yes",
          "13": "Cancle",
          "14" : "Chose Product",
          "15" : "Easy And Safe Payment",
          "16": "Fast Delivery",
          "17" : "We have a 100K product, choose \n your product from our \n chocolate_shop.",
          "18" : "Products",
          "19" : "Login",
          "20" : "Email",
          "21" : "Please enter Email",
          "22" : "password",
          "23" : "Please enter password",
          "24" : "Forgot Your Password?",
          "25" : "Does not have an account?",
          "26" : "Sign Up",
          "27" : "Forgot Password",
          "28" : "Enter your email for the verification proccess , we will send 4 digits code to your email.",
          "29" : "Enter 4 Digits Code",
          "30" : "Enter the 4 digits code \n that you received on your email.",
          "31" : "Code",
          "32" : "Please The Code is not correct",
          "33" : "Create new Account",
          "34" : "please fill the input blow here",
          "35" : "First Name",
          "36" : "Please enter First Name",
          "37" : "Please enter last Name",
          "38" : "Last Name",
          "39" : "Create Account",
          "40" : "Phone number",
          "41" : "Please enter Phone number",
          "42" : "Reset Password ",
          "43" : "Set the new password for your account so you can login and access all the features.",
          "44" : "Enter confirm password",
        }
      };
}
